### ISSUE TITLE
Crash with High Oven Controller

### ISSUE THREAD

**Issue by Yorkforce** [Toops/TinkersSteelworks#6]
Were currently using the Agrarian Skies 2.0.3 mod on our server, each time anyone tries to open the High Oven controller thier inventory get rearranged with some items going inside the high over controllers inventory. When attempting to pick any items up that were moved the client crashes with an Internal Server error.

This is this following error report in the console:
[WARNING] Failed to handle packet for xYorkx/(ommited IP): java.lang.IndexOutOfBoundsException: Index: 40, Size: 40
java.lang.IndexOutOfBoundsException: Index: 40, Size: 40
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at net.minecraft.inventory.Container.func_75144_a(Container.java:404)
    at net.minecraft.network.NetServerHandler.func_72523_a(NetServerHandler.java:2094)
    at net.minecraft.network.packet.Packet102WindowClick.func_73279_a(Packet102WindowClick.java:46)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

**Comment by Toops** [comment]
Working on that now. Thanks for the report!

**Comment by Toops** [comment]
Hmmm... you wouldn't happen to be using MCPC, would you?

**Comment by wisthy** [comment]
based on other issues submited by him/her, he/she is admin on an MCPC+ server so I think you can assume this issue is on an MCPC+ environment.

**Comment by Toops** [comment]
Ah, well that would explain it. I had my suspicions when I saw an identical crash and inventory flying everywhere with the smeltery. 

Unfortunately, support for MCPC+ is beyond the scope of this mod, especially considering TConstruct doesn't have any specialized support for MCPC+ within TConstruct itself.

You may consider taking it up with the MCPC+ devs, however. For now, we're gonna consider this resolved.
